site_name: Archiving Subsystem for Moodle
site_url: "https://archiving.gandrass.de/"
use_directory_urls: !ENV [OFFLINE, true]
repo_url: https://github.com/ngandrass/moodle-local_archiving
edit_uri: edit/master/docs/

copyright: "Copyright &copy; 2025 Niels Gandraß<br>License: GNU General Public License v3.0"

extra:
  social:
    - icon: simple/matrix
      link: https://matrix.to/#/#archiving:gandrass.de
      name: "Matrix room: #archiving:gandrass.de"
    - icon: material/bug
      link: https://github.com/ngandrass/moodle-local_archiving/issues
      name: "Issue Tracker"
    - icon: fontawesome/brands/github
      link: https://github.com/ngandrass/moodle-local_archiving
      name: "GitHub Repository"
#    - icon: simple/moodle
#      link: https://moodle.org/plugins/quiz_archiver
#      name: "Moodle Plugin Directory: quiz_archiver"
#    - icon: fontawesome/brands/github
#      link: https://github.com/ngandrass/moodle-quiz_archiver
#      name: "GitHub: moodle-quiz_archiver"
#    - icon: fontawesome/brands/github
#      link: https://github.com/ngandrass/moodle-quiz-archive-worker
#      name: "GitHub: moodle-quiz-archive-worker"
  demand_mandatory: "<span style='float:right; font-weight: 400;'>Mandatory <span style='color:#C62828;'>:material-alert:</span></span>"
  demand_high: "<span style='float:right; font-weight: 400;'>High Demand <span style='color:#FF5722;'>:material-circle:</span></span>"
  demand_medium: "<span style='float:right; font-weight: 400;'>Medium Demand <span style='color:#FFC107;'>:material-circle:</span></span>"
  demand_low: "<span style='float:right; font-weight: 400;'>Basic Demand <span style='color:#689F38;'>:material-circle:</span></span>"
  moodle_component_manager: "local_archive"
  todo: "{== **TODO** ==}"

#   version:
#     provider: mike

plugins:
  # - mike
  - drawio
  - glightbox:
      shadow: true
  - macros:
      module_name: mkdocs-macros
      on_error_fail: true
  - offline:
      enabled: !ENV [OFFLINE, false]
  - panzoom:
      key: "shift"
  - privacy
  - search
  - social

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - search.suggest
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/extra.css

nav:
  - "Introduction": index.md
  - "Components": components.md
  - "Roadmap": roadmap.md
  - "Screenshots": screenshots.md
  - "Changelog": changelog.md

  - "Setup":
    - "Installation":
        - setup/install/index.md
        - "Archiving Core": setup/install/core.md
        - setup/install/plugins.md
    - "Configuration":
      - setup/config/index.md
      - setup/config/general.md
      - setup/config/components.md
      - setup/config/job-presets.md
      - setup/config/archive-signing.md
    - setup/index.md

  - "Usage":
      - usage/index.md
      - usage/overview.md
      - usage/archive-creation.md
      - usage/download.md
      - usage/logs.md

  - "Developer Documentation":
    - dev/index.md
    - "Requirements and Specifications":
      - dev/requirements/index.md
      - "Existing Solutions": dev/requirements/existing-solutions.md
      - "Data Analysis": dev/requirements/data-analysis.md
      - "User Stories": dev/requirements/user-stories.md
      - "Base Requirements": dev/requirements/base-requirements.md
    - "Components":
      - dev/components/index.md
      - dev/components/archiving-manager.md
      - dev/components/activity-archiving-drivers.md
      - dev/components/worker-services.md
      - dev/components/storage-drivers.md
      - dev/components/archiving-triggers.md
      - dev/components/external-event-connectors.md
    - "Interfaces (APIs) and Signals":
      - dev/api/index.md
      - dev/api/archive-job-states.md
      - dev/api/events.md
      - dev/api/activity-archiving-drivers.md
      - dev/api/storage-drivers.md
      - dev/api/archiving-triggers.md
      - dev/api/external-event-connectors.md
    - "Testing":
      - dev/testing/index.md
    - dev/builddocs.md
